name: Pipeline git commands
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/pipeline-git-commands.yaml

jobs:
  pipeline-git-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Dump environment variables
        run: export

      - name: Run git commands
        run: |
          set -x
          git log --oneline --all --graph
          git status
          git tag $(date +%Y-%m-%d_%H-%M-%S) HEAD
          date > release-date
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add release-date
          git commit -m "Update release date"
          #git push --tags
          git push --tags https://github.com/askoriy/test-github-actions2.git HEAD:master
          echo test2
